[package]
name = "sgxdcnet-server"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "sgxdcnet-server"
path = "src/main.rs"

[dependencies]
interface = { path = "../interface" }
common = {path = "../common"}
base64 = "0.13"
serde = "1.0"
clap = "2.33"
