[package]
name = "sgxdcnet-aggregator"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "sgxdcnet-aggregator"
path = "src/main.rs"

[dependencies]
interface = { path = "../interface" }
common = {path = "../common"}
clap = "2.33"
serde = "1.0"
