name: Build
on: push
env:
  LD_RUN_PATH: /usr/lib:/usr/local/lib
  LD_LIBRARY_PATH: /usr/lib:/usr/local/lib:/opt/sgxsdk/sdk_libs
  PATH: "/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/sgxsdk/bin:/opt/sgxsdk/bin/x64"
jobs:
  format:
    runs-on: ubuntu-20.04
    container:
      image: bl4ck5un/sgx-rust-fork:2004-1.1.6
      env:
        SGX_MODE: SW
        SGX_SDK: /opt/sgxsdk
    steps:
      - uses: actions/checkout@v2
      - name: fmt check
        run: cargo fmt --check
      - name: fmt check enclave
        run: cargo fmt --check
        working-directory: ./enclave
  linter:
    runs-on: ubuntu-20.04
    container:
      image: bl4ck5un/sgx-rust-fork:2004-1.1.6
      env:
        SGX_MODE: SW
        SGX_SDK: /opt/sgxsdk
    steps:
      - uses: actions/checkout@v2
      - name: clippy
        run: cargo clippy
      - name: clippy on enclave
        run: cargo clippy
        working-directory: ./enclave
  build-everything:
    runs-on: ubuntu-20.04
    container:
      image: bl4ck5un/sgx-rust-fork:2004-1.1.6
      env:
        SGX_MODE: SW
        SGX_SDK: /opt/sgxsdk
    steps:
      - uses: actions/checkout@v2
      - name: Build enclave
        run: make
        working-directory: ./enclave
      - name: Run test
        run: bash ./run_tests.sh
