name: Build
on: push

jobs:
  build-everything:
    runs-on: ubuntu-20.04
    container:
      image: bl4ck5un/sgx-rust-fork:2004-1.1.6
      env:
        SGX_MODE: SW
        SGX_SDK: /opt/sgxsdk
    steps:
      - uses: actions/checkout@v2
      - name: Build enclave
        run: PATH=/root/.cargo/bin:$PATH make
        working-directory: ./enclave
      - name: Build client
        run: PATH=/root/.cargo/bin:$PATH cargo b
        working-directory: ./enclave
      - name: Run test
        run: bash ./run_tests.sh
