name: Build
on: push
env:
  LD_RUN_PATH: /usr/lib:/usr/local/lib
  LD_LIBRARY_PATH: /usr/lib:/usr/local/lib:/opt/sgxsdk/sdk_libs
  PATH: "/root/:cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/sgxsdk/bin:/opt/sgxsdk/bin/x64"
jobs:
  build-everything:
    runs-on: ubuntu-20.04
    container:
      image: bl4ck5un/sgx-rust-fork:2004-1.1.6
      env:
        SGX_MODE: SW
        SGX_SDK: /opt/sgxsdk
    steps:
      - uses: actions/checkout@v2
      - name: Build enclave
        run: PATH=/root/.cargo/bin:$PATH make
        working-directory: ./enclave
      - name: Build client
        run: PATH=/root/.cargo/bin:$PATH cargo b
        working-directory: ./enclave
      - name: Run test
        run: bash ./run_tests.sh
